apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "2"
  source:
    git:
      url: https://github.com/somarajuvvj/tapdemo
      ref:
        branch: main
